### ISSUE TITLE
Missing guide

### ISSUE THREAD

**Issue by Albertringwood** [JingyaoDOU/woma0#2]
Dear Dr. Dao
Among your repositories I remember having seen one where there was a very useful guide to using Woma and swiftsim, however, I can not find it anymore because deleted. Is it possible to reach it?
Let me know and thank you.
Albert.

**Comment by JingyaoDOU** [comment]
Hi Albert,

Sorry for the late reply, I'm traveling these days. You can now find the previous guide under https://github.com/JingyaoDOU/SWIFT_share_public/tree/main/use_guide.

Please let me know if you have further issues.

Cheers,

Jingyao

**Comment by Albertringwood** [comment]
No problems Dr. Dao, thank you very much for you help!
Albert
